version: '3.8'

networks:
  app-network:
    driver: bridge
    internal: false

volumes:
  node_modules:
  mysql_data:
    driver: local

services:
  web:
    build:
      context: ./
      args:
        - NODE_ENV=${NODE_ENV:-development}
    image: sport-buddy-web
    container_name: sport-buddy-web
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - ./src/views:/app/src/views
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-Sport_Buddy}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASS=${MYSQL_PASS:-password}
      - PORT=8000
      - SESSION_SECRET=${SESSION_SECRET:-sport-buddy-secret-key}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/api/debug"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 200M
    security_opt:
      - no-new-privileges:true

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: sport-buddy-db
    restart: always
    env_file:
      - ./config/.env
    environment:
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-Sport_Buddy}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=64M --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 250M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: sport-buddy-phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=${MYSQL_USER:-admin}
      - PMA_PASSWORD=${MYSQL_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - UPLOAD_LIMIT=300M
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
